apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ahe-app
  template:
    metadata:
      labels:
        app: ahe-app
    spec:
      containers:
      - name: ahe-app-container
        image: konfle/ahe-app:latest
        ports:
        - containerPort: 80