apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ahe-app
  template:
    metadata:
      labels:
        app: ahe-app
    spec:
      containers:
      - name: ahe-app-container
        image: konfle/ahe-app:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: fastapi
        ports:
        - containerPort: 80
