apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-17T18:16:29Z"
  name: ahe-app
  namespace: default
  resourceVersion: "5875"
  uid: efcf500e-2183-499a-9f00-1ba5769a3548
spec:
  clusterIP: 10.108.252.252
  clusterIPs:
  - 10.108.252.252
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32282
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ahe-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}